kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-arena-ords-proxy-q1
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  ingresses:
    - https://amt-arena-ords-proxy-q1.dev-fss-pub.nais.io
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    disableAutoScaling: true
    min: 1
    max: 1
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      memory: 1024Mi
  azure:
    application:
      enabled: true
  env:
    - name: ARENA_ORDS_URL
      value: https://arena-ords-q1.nais.preprod.local
  envFrom:
    - secret: amt-arena-ords-proxy
  accessPolicy:
    inbound:
      rules:
        - application: aktivitet-arena-acl
          namespace: dab
          cluster: dev-gcp
