kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-arena-ords-proxy
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  ingresses:
    - https://amt-arena-ords-proxy.prod-fss-pub.nais.io
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    scalingStrategy:
      cpu:
        thresholdPercentage: 200
  resources:
    requests:
      cpu: 20m
      memory: 356Mi
    limits:
      memory: 1024Mi
  azure:
    application:
      enabled: true
  env:
    - name: ARENA_ORDS_URL
      value: https://arena-ords.nais.adeo.no
  envFrom:
    - secret: amt-arena-ords-proxy
  accessPolicy:
    inbound:
      rules:
        - application: amt-arena-acl
          namespace: amt
          cluster: prod-gcp
        - application: aktivitet-arena-acl
          namespace: dab
          cluster: prod-gcp
        - application: mulighetsrommet-arena-adapter
          namespace: team-mulighetsrommet
          cluster: prod-gcp
